---
title: "Generate Causality SIF"
output:
  html_notebook: default
  html_document:
    toc: yes
  pdf_document:
    toc: yes
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
require("knitr")
opts_knit$set(root.dir="..")
opts_chunk$set(fig.align="center", fig.width=6, fig.height=6, dpi=300)

```

## Purpose
* Plot SIFs generated by the Causality analysis

## Setup 
```{r loadLibraries, message=FALSE, warning=FALSE}
library(zeptosensPkg)
library(paxtoolsr)
library(igraph)
```

## Generate SIF File
```{r}
graphType <- "compatible"
signedPcDir <- tempdir()
results <- generateRPPAGraphs(platformFile = "inst/chibeExample/abdata-chibe.txt", 
                              idColumn = "ID1", 
                              symbolsColumn = "Symbols",  
                              sitesColumn = "Sites",
                              effectColumn = "Effect", 
                              valuesFile = "inst/chibeExample/ovcar4_dif_drug_sig.txt", 
                              valueColumn = "change", 
                              valueThreshold = 0.001,
                              graphType = graphType, 
                              siteMatchStrict=TRUE,
                              outputFilePrefix = "inst/chibeExample/ovcar4_dif_drug_sig_compatible",
                              customNetworkDirectory=signedPcDir)

compatibleSif <- results$sif
compatibleSif[, "graphType"] <- rep(graphType,  nrow(results$sif))

graphType <- "conflicting"
results <- generateRPPAGraphs(platformFile = "inst/chibeExample/abdata-chibe.txt", 
                              idColumn = "ID1", 
                              symbolsColumn = "Symbols",  
                              sitesColumn = "Sites",
                              effectColumn = "Effect", 
                              valuesFile = "inst/chibeExample/ovcar4_dif_drug_sig.txt", 
                              valueColumn = "change", 
                              valueThreshold = 0.001,
                              graphType = graphType, 
                              siteMatchStrict=TRUE,
                              outputFilePrefix = "inst/chibeExample/ovcar4_dif_drug_sig_conflicting",
                              customNetworkDirectory=signedPcDir)

conflictingSif <- results$sif
conflictingSif[, "graphType"] <- rep(graphType,  nrow(results$sif))

overallSif <- rbind(conflictingSif, compatibleSif)
```

## Parse SIF 
```{r}
t1 <- conflictingSif[, c("PARTICIPANT_A", "INTERACTION_TYPE", "PARTICIPANT_B")]
t2 <- t1[t1$INTERACTION_TYPE != "",]
g <- loadSifInIgraph(t2)

# Get node colors
formatTmp <- subset(results$format, componentProperty == "color" & componentType == "node", select = c(componentLabel, rgbColor))

nodeColors <- NULL 

for(i in 1:length(V(g))) {
    idx <- which(formatTmp[, "componentLabel"] == V(g)$name[i])
    
    if(length(idx) == 1) {
        rgbTmp <- strsplit(formatTmp[idx, "rgbColor"], " ")[[1]]
        
        # Values must be between 0 and 1
        t1 <- as.numeric(rgbTmp) / 255
        hexColor <- do.call("rgb", as.list(t1))
        
        nodeColors <- c(nodeColors, hexColor)
    } else {
        nodeColors <- c(nodeColors, "#FFFFFF")
    }
}

# Get edge colors 
formatTmp <- subset(results$format, componentProperty == "color" & componentType == "edge", select = c(componentLabel, rgbColor))

edgeColors <- NULL 
edgeLty <- NULL

for(i in 1:length(E(g))) {
    label <- paste(ends(g, E(g)[i])[1], E(g)[i]$edgeType, ends(g, E(g)[i])[2], sep=" ")
    idx <- which(formatTmp[, "componentLabel"] == label)
    
    if(length(idx) == 1) {
        rgbTmp <- strsplit(formatTmp[idx, "rgbColor"], " ")[[1]]
        t1 <- as.numeric(rgbTmp) / 255
        hexColor <- do.call("rgb", as.list(t1))
        
        edgeColors <- c(edgeColors, hexColor)
        
        if(E(g)[i]$edgeType == "phosphorylates") {
            edgeLty <- c(edgeLty, 2)            
        } else {
            edgeLty <- c(edgeLty, 1) 
        }
    } else {
        edgeColors <- c(edgeColors, "#FFFFFF")
    }
}

V(g)$color <- nodeColors
E(g)$color <- edgeColors
E(g)$lty <- edgeLty
```

## Plot SIF
```{r}
plot(g, layout=layout.fruchterman.reingold, 
     edge.arrow.width=0.5, edge.arrow.size=0.5, edge.color=E(g)$color, edge.lty=E(g)$lty,
     vertex.color=V(g)$color, vertex.label.cex=0.5)
```









