#' Rescale between 0-1
#' 
#' @description  Map the distance matrices for all data types to 0-1 
#' 
#' @param x a numeric vector of values 
#' 
#' @return a rescaled numeric vector of values  
#' 
#' @export
convert_to_0_to_1_using_xminusmin_by_maxminusmin <- function(x) { (x-min(x))/(max(x)-min(x)) }

#' Make Balloon Plot Data from Run Comparison Function
#' 
#' @param comparison_result a data structure generated by run_comparison() function
#' 
#' @description   Code to convert the output of TC for a single cancer type to balloon plots. We
#'   don't use ranks here, since some cell lines will get low ranks even if none have particularly
#'   low scores (similarly some will get high ranks even if all scores are relatively low). Instead,
#'   we convert the distance matrices for all tumor-cell line comparisons to 0-1 using min-max
#'   scaling, and then compute the mean similarity to tumor for each cell line. The overall score is
#'   just a simiple mean of the data type specific scores right now - could use different weights
#'   
#' @return a ggplot object
#' 
#' @importFrom ggplot2 ggplot geom_point geom_text ggtitle xlab ylab element_blank element_line
#' @importFrom dplyr mutate 
#' @importFrom reshape2 melt 
#' @importFrom stats reorder
#' @importFrom magrittr %>%
#' 
#' @export 
make_balloon_plot_data_from_comparison_result <- function(comparison_result) {
  #mean_similarity_to_tumors_after_0to1_scaling_MUT <- round(1 - rowMeans(apply(comparison_result$dist_mat_by_data_type$mut,2,convert_to_0_to_1_using_xminusmin_by_maxminusmin)[comparison_result$cell_line_ids,comparison_result$tumor_ids],na.rm=T),digits=2)
  #mean_similarity_to_tumors_after_0to1_scaling_EXP <- round(1 - rowMeans(apply(comparison_result$dist_mat_by_data_type$exp,2,convert_to_0_to_1_using_xminusmin_by_maxminusmin)[comparison_result$cell_line_ids,comparison_result$tumor_ids],na.rm=T),digits=2)
  #mean_similarity_to_tumors_after_0to1_scaling_CNA <- round(1 - rowMeans(apply(comparison_result$dist_mat_by_data_type$cna,2,convert_to_0_to_1_using_xminusmin_by_maxminusmin)[comparison_result$cell_line_ids,comparison_result$tumor_ids],na.rm=T),digits=2)
  
  cell_line_ids <- comparison_result$cell_line_ids 
  tumor_ids <- comparison_result$tumor_ids
  
  available_data_types <- names(comparison_result$dist_mat_by_data_type)
  
  mean_similarity_to_tumors_scaling_mat <- matrix(rep(NA, length(cell_line_ids)*length(available_data_types)), 
                                                  ncol=length(available_data_types), 
                                                  dimnames = list(cell_line_ids, paste0(available_data_types, "_score")))
  
  for(i in 1:length(available_data_types)) {
    #i <- 1 
    
    data_type <- available_data_types[1]
    #data_type <- "mut"
    cur_data <- comparison_result$dist_mat_by_data_type[[data_type]]
      
    # This is a vector 
    mean_similarity_to_tumors_scaling_mat[,i] <- round(1 - rowMeans(apply(cur_data[cell_line_ids,tumor_ids],2,convert_to_0_to_1_using_xminusmin_by_maxminusmin), na.rm=T), digits=2)
  }
  
  #mean_similarity_to_tumors_after_0to1_scaling_MUT <- round(1 - rowMeans(apply(comparison_result$dist_mat_by_data_type$mut[comparison_result$cell_line_ids,comparison_result$tumor_ids],2,convert_to_0_to_1_using_xminusmin_by_maxminusmin),na.rm=T),digits=2)
  #mean_similarity_to_tumors_after_0to1_scaling_CNA <- round(1 - rowMeans(apply(comparison_result$dist_mat_by_data_type$cna[comparison_result$cell_line_ids,comparison_result$tumor_ids],2,convert_to_0_to_1_using_xminusmin_by_maxminusmin),na.rm=T),digits=2)
  #mean_similarity_to_tumors_after_0to1_scaling_EXP <- round(1 - rowMeans(apply(comparison_result$dist_mat_by_data_type$exp[comparison_result$cell_line_ids,comparison_result$tumor_ids],2,convert_to_0_to_1_using_xminusmin_by_maxminusmin),na.rm=T),digits=2)

  average_mean_similarity_scaling <- rowMeans(mean_similarity_to_tumors_scaling_mat)
  #average_mean_similarity_after_0to1_scaling <- round((mean_similarity_to_tumors_after_0to1_scaling_MUT + mean_similarity_to_tumors_after_0to1_scaling_CNA + mean_similarity_to_tumors_after_0to1_scaling_EXP)/3, digits=2)
  
  heatmap_mat <- as.data.frame(mean_similarity_to_tumors_scaling_mat)
  heatmap_mat$cell_line_name <- cell_line_ids
  heatmap_mat$avg_mean_similarity <- average_mean_similarity_scaling
  
  # heatmap_mat <- as.data.frame(
  #   cbind(names(average_mean_similarity_after_0to1_scaling), mean_similarity_to_tumors_after_0to1_scaling_MUT, mean_similarity_to_tumors_after_0to1_scaling_CNA, mean_similarity_to_tumors_after_0to1_scaling_EXP, average_mean_similarity_after_0to1_scaling))
  #heatmap_mat[,-1] <- apply(heatmap_mat[,-1],2,as.numeric)
  #heatmap_mat[,-1] <- round(heatmap_mat[,-1],digits=2)
  #colnames(heatmap_mat) <- c("Cell_Line_Name","MUT_score","CNA_score","EXP_score","Combined_score")

  df <- melt(heatmap_mat, id.vars = "cell_line_name")
  
  return(df)
}

#' Make Balloon Plot from MTC Data structure 
#' 
#' @param mtc TODO FIXME DESCRIBE ME EACH COLUMN AND DATA TYPE
#' @param cancer_type a cancer type abbreviation found in the MTC column Cell_Line_Cancer_Type
#' 
#' @description Code to convert the processed output of TC over a pan-cancer dataset balloon plots
#'   for a single cancer type ("current_cancer_type") MTC - The subset of TC's output on a
#'   pan-cancer dataest which contains results for matched cancer type, i.e. for each cell line, it
#'   rreports the results when compared to tumors of the same cancer type So, for example, if we run
#'   TC on 10 cancer types on a pan-cancer type, we get 10 sets of results, with each set containing
#'   the results of comparing one of the 10 cancer types to all cell lines From this, MTC extracts
#'   only the results where the cell line and tumors are of the same cancer type, using the other
#'   cell lines to derive ranks We use ranks to compare across cancer types, since the weights and
#'   score distributions are very different across data types and  cancer types
#'   
#' @return a ggplot object
#' 
#' @importFrom ggplot2 ggplot geom_point geom_text ggtitle xlab ylab element_blank element_line
#' @importFrom dplyr mutate 
#' @importFrom reshape2 melt 
#' @importFrom stats reorder
#' @importFrom magrittr %>%
#' 
#' @export 
make_balloon_plot_data_from_mtc <- function(mtc, cancer_type) {
  selected_columns <- c("Cell_Line_Name", "MUTSIM_Percentile_Ranks", "CNASIM_Percentile_Ranks", "EXPSIM_Percentile_Ranks", "Rank_of_Average_Of_Percentile_Ranks")
  
  mat_for_heatmap <- mtc[which(mtc$Cell_Line_Cancer_Type == cancer_type), selected_columns]
  mat_for_heatmap[,-1] <- apply(mat_for_heatmap[,-1],2,as.numeric)
  mat_for_heatmap[,-1] <- round(mat_for_heatmap[,-1],digits=2)
  colnames(mat_for_heatmap)[2:4] <- c("MUTSIM_Ranks", "CNASIM_Ranks", "EXPSIM_Ranks")
  colnames(mat_for_heatmap)[5] <- "Combined_Score_Ranks"

  df <- melt(mat_for_heatmap, id.vars = "Cell_Line_Name")
  
  return(df)
}
